### ISSUE TITLE
Purchase Ticket

### ISSUE THREAD

**Issue by DXCDandelion** [dxcCorey/dwep-2dw-base#2]
The customer should be able to purchase an airline ticket from the robot.

### Pre-requisites

- Customer has registered their details at the pre-registration site.
- Customer has their Nao Mark with them.
- Credit card processing available.
- Tax invoice template available.

### Happy Flow

- [ ] Robot detects someone has approached him
- [ ] Robot asks how he can help them, providing options
- [ ] Customer chooses purchase ticket option
- [ ] Robot asks customer where they would like to go, providing options
- [ ] Customer chooses option
- [ ] Robot provides price(see pricing table) and asks to confirm
- [ ] Customer says OK
- [ ] Robot asks customer for their Nao Mark ID
- [ ] Customer shows robot their Nao Mark ID
- [ ] Robot retrieves customer's details
- [ ] Robot performs security check (using security check feature #6)
- [ ] Robot processes transaction
- [ ] Robot confirms to customer
- [ ] Ticket is created using template and emailed to customer
- [ ] Robot confirms flight departure and wans customer that they must check in 30 mins before departure

- [ ] Robot asks if there is anything else the customer requires

#### Repeat

- [ ] At any time the customer can ask to repeat the question/options

#### Credit card declined

- [ ] Inform customer, ask them to check their details on the pre-registration site

#### Security check fail

- [ ] Ask customer to wait here
- [ ] Robot informs security (using security check feature #6)

#### Nao Mark not recognised

- [ ] Ask customer to show again, max 3 retries
- [ ] Robot informs security (using security check feature #6)

#### Customer details could not be retrieved

- [ ] Notify customer there was a problem
- [ ] Contact system administrator

#### Email of tax invoice fails

- [ ] Notify customer there was a problem
- [ ] Contact system administrator

### Pricing Table
Destination | Price per ticket | Daily departure time
------------- | ---------------- | -----------------------
Sydney | $123.76 | 08:55
Brisbane | $321.87 | 09:45
Melbourne | $244.98 | 07:30
Darwin | $452.66 | 11:15
Adelaide | $231.96 | 13:35
Perth | $367.54 | 06:20
Hobart | $345.77 | 14:50
Canberra | $367.43 | 16:10

- [ ] All bookings attract a $10.95 booking fee

**Comment by DXCDandelion** [comment]
Kamino cloned this issue to dxcCorey/CBR-2DW-18-1
