### ISSUE TITLE
Customer Checkin

### ISSUE THREAD

**Issue by DXCDandelion** [dxcCorey/dwep-2dw-base#3]
The customer receives a boarding pass once they check in.

### Pre-requisites

- Customer has purchased a ticket from the robot.
- Customer has their ticket with them.

### Happy Flow

- [ ] Robot detects someone has approached him
- [ ] Robot asks how he can help them, providing options
- [ ] Customer chooses check in option
- [ ] Robot asks customer for their ticket
- [ ] Customer shows robot their ticket
- [ ] Robot performs security check (using security check feature #6)
- [ ] Robot creates boarding pass and emails it to the customer
- [ ] Robot gives boarding time and at which gate
- [ ] Robot gives directions to gate (using directions feature #4 )
- [ ] Robot asks if there is anything else the customer requires

#### Repeat

- [ ] At any time the customer can ask to repeat the question/options

#### No ticket purchases found

- [ ] Robot informs the customer they cannot find a matching ticket purchase and they should contact the customer service desk

#### Check in attempt after cutoff time (see #2 for departure times)

- [ ] Robot informs the customer they have missed the check in window and they should contact the customer service desk

#### Customer already checked in

- [ ] Robot informs customer they have already checked in
- [ ] Provides customer with departure gate and time

#### Security check fail

- [ ] Ask customer to wait here
- [ ] Robot informs security (using security check feature #6)

#### Email of boarding pass fails

- [ ] Notify customer there was a problem
- [ ] Contact system administrator

**Comment by DXCDandelion** [comment]
Kamino cloned this issue to dxcCorey/CBR-2DW-18-1
