### ISSUE TITLE
Customer Security Check

### ISSUE THREAD

**Issue by DXCDandelion** [dxcCorey/dwep-2dw-base#6]
A background process to check if the customer is registered as a security risk.

### Pre-requisites
- Security data exists

### Security Check

- [ ] For the given ID, look up the security database
- [ ] If record exists, analyse threat level
   - [ ] If RED, notify security team with code ![#f03c15](https://placehold.it/15/f03c15/000000?text=+) RED and that they should respond immediately
   - [ ] If YELLOW, notify security team with code ![#f4f442](https://placehold.it/15/f4f442/000000?text=+) YELLOW and that they should place person on watch
- [ ] Respond to calling process with code
- [ ] If no record exists, respond to calling process with code ![#41f441](https://placehold.it/15/41f441/000000?text=+) GREEN

### Triggers

- [ ] When showing Nao Mark ID for ticket purchase #2 
- [ ] When showing boarding pass for check in #3

**Comment by DXCDandelion** [comment]
Kamino cloned this issue to dxcCorey/CBR-2DW-18-1
